EMBEDDING_MODEL : "text-embedding-3-small"
EMBEDDING_API_URL : "https://api.openai.com/v1/embeddings"
MY_TOKEN : "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"
PERSIST_DIR : "./chroma_db4"
COLLECTION : "kai_tech4"
DISTANCE : "cosine"
LLM_MODEL : "gpt-4.1"
LLM_API_URL : "https://api.openai.com/v1/chat/completions"